name: 'tf-kubernetes-addons'

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  terraform-pre-commit:
    name: 'terraform:pre-commit'
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4

    - name: 'asdf:install'
      uses: asdf-vm/actions/install@v1

    - name: Check modules
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --show-diff-on-failure --all-files
